import {readFileSync,existsSync} from 'node:fs';
import assert from 'node:assert/strict';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
assert.match(html,/<form id="unlock-form">/);
assert.match(html,/type="password"/);
assert.match(html,/const encryptedPage='[A-Za-z0-9+/=]+';/);
assert.ok(!/<details|teamLab|Okachimachi|Shibuya|Nagamachi|ICOCA/.test(html),'Keine Reiseinhalte im Klartext');
assert.ok(!/localStorage|fetch\(/.test(html),'Kein Speichern oder Versenden des Passworts');
assert.match(html,/sessionStorage/,'Sitzung bleibt im aktuellen Tab entsperrt');
assert.ok(!/sessionStorage\.setItem\([^,]+,field\.value\)/.test(html),'Das Passwort wird nicht gespeichert');
assert.ok(!existsSync(new URL('../data/reise.json',import.meta.url)),'Alte öffentliche Reisedaten entfernen');
assert.ok(!existsSync(new URL('../data/previous-master.md',import.meta.url)),'Alte öffentliche Reiseversion entfernen');
console.log('Verschlüsselte eigenständige Seite und entfernte Klartextdaten geprüft.');
